### ISSUE TITLE
Check on quit working/not-working depending on VIM version

### ISSUE THREAD

**Issue by techraf** [scrooloose/syntastic#1813] opened 2016-07-14 09:54 UTC
OS X El Capitan, latest Syntastic build.

My `.vimrc` entries related to Syntastic:
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

VIM 7.3 (El Capitan) ignores `let g:syntastic_check_on_wq = 0` and **always** performs check-on-quit. Setting `let g:syntastic_check_on_open = 0` disables **both** check on open **and** check-on-quit.

VIM 7.4 (Homebrew) ignores `let g:syntastic_check_on_wq = 1` and **never** performs check-on-quit (*edit: later I found that by design Syntastic might not perform the check-on-quit when the file was not modified in Vim, so this info might be biased by comparing to the above 7.3 experience*).

**Comment by lcd047** [comment] 2016-07-14 10:04
Not all combinations of Vim compilation options and versions allow you to use all features of syntastic.  `g:syntastic_check_on_wq` relies on the `QuitPre` autocmd, that has been added in Vim 7.3.544.  Please post the output of `vim --version`.

Also, please open a file in Vim, run `:SyntasticInfo`, and post the output.

**Comment by techraf** [comment] 2016-07-14 14:40
The situation is more complicated than I assumed (neither the native, old version of Vim, nor the newest work, but I had interim version which seemed to work). Let's troubleshoot the newest:

- ignores let g:syntastic_check_on_wq = 0
- always performs check on quit (regardless if file changed or not)
- let g:syntastic_check_on_open = 0 disables both check on open and check on quit

```
# vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  7 2016 14:56:14)
MacOS X (unix) version
Included patches: 1-1993
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +find_in_path    +mouse_urxvt     -tcl
+autocmd         +float           +mouse_xterm     +termguicolors
-balloon_eval    +folding         +multi_byte      +terminfo
-browse          -footer          +multi_lang      +termresponse
++builtin_terms  +fork()          -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +packages        -toolbar
-clientserver    +insert_expand   +path_extra      +user_commands
+clipboard       +job             +perl            +vertsplit
+cmdline_compl   +jumplist        +persistent_undo +virtualedit
+cmdline_hist    +keymap          +postscript      +visual
+cmdline_info    +langmap         +printer         +visualextra
+comments        +libcall         +profile         +viminfo
+conceal         +linebreak       +python          +vreplace
+cryptv          +lispindent      -python3         +wildignore
+cscope          +listcmds        +quickfix        +wildmenu
+cursorbind      +localmap        +reltime         +windows
+cursorshape     -lua             +rightleft       +writebackup
+dialog_con      +menu            +ruby            -X11
+diff            +mksession       +scrollbind      -xfontset
+digraphs        +modify_fname    +signs           -xim
-dnd             +mouse           +smartindent     -xsmp
-ebcdic          -mouseshape      +startuptime     -xterm_clipboard
+emacs_tags      +mouse_dec       +statusline      -xterm_save
+eval            -mouse_gpm       -sun_workshop    -xpm
+ex_extra        -mouse_jsbterm   +syntax
+extra_search    +mouse_netterm   +tag_binary
+farsi           +mouse_sgr       +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/Cellar/python/2.7.12/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1/lib
```

```
:SyntasticInfo
Syntastic version: 3.7.0-162 (Vim 703, Darwin)
Info for filetype:
Global mode: active
Filetype  is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
The current file will not be checked (file not readable / not local)
```

**Comment by lcd047** [comment] 2016-07-14 15:03
> Let's troubleshoot the newest first:

Ok, please make sure you're using only Vim 7.4.1993 and the latest (unmodified) version of syntastic.  Disable all other plugins (f.i. move them elsewhere), and add this line to your `vimrc`:
```vim
let check_on_open = 1
let g:syntastic_debug = 9
```
Then open a file that should be checked and has at least one problem reported by syntastic, run `:mes`, and post the output.

**Comment by techraf** [comment] 2016-07-14 22:32
My `.vimrc`:

```
execute pathogen#infect()

syntax on

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let check_on_open = 1
let g:syntastic_debug = 9
```

My `test.sh`:
```
echo `whoami`
```

When running `vi test.sh`:
```
syntastic: 0.063154: getLocList: checker sh/shellcheck run in 0.021749s
syntastic: 0.065927: autocmd: BufEnter, buffer 1 = 'test.sh', &buftype = ''
Press ENTER or type command to continue
```

Shellcheck was run on quitting Vim, after `vi test.sh` then `Enter` (to confirm above) + `:q` (immediately, i.e. without making change to the file).

**Comment by techraf** [comment] 2016-07-14 23:35
**Tangential**

I managed to get the version of the Vim on which Syntastic behaved differently to Vim 7.4.1993.

```
# /usr/local/Cellar/vim/7.4.1967/bin/vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 30 2016 15:56:05)
MacOS X (unix) version
Included patches: 1-1967
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +termguicolors
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+channel         -gettext         -mzscheme        +textobjects
+cindent         -hangul_input    +netbeans_intg   +timers
-clientserver    +iconv           +packages        +title
+clipboard       +insert_expand   +path_extra      -toolbar
+cmdline_compl   +job             +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/Cellar/python/2.7.12/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1/lib
```

With this version the check-on-quit did not happen (however I have not checked if it did when the file was modified). I will try to reinstall this version and test later.

**Comment by lcd047** [comment] 2016-07-15 07:22
Please use a single version of Vim.  For Vim 7.4, it should make a difference if you're using 7.4.1639 or earlier, or 7.4.1640 or newer.  Other variations shouldn't be relevant to syntastic.

Please try again with this configuration:
```vim
execute pathogen#infect()

syntax on

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_sh_checkers = ['shellcheck']

let g:syntastic_debug _file = '~/syntastic.log'
let g:syntastic_debug = 9
```
Open the test file, then quit it with `:wq`.  This will create a log file `~/syntastic.log`, please post its contents.  Then repeat for the other combinations of `check_on_open` and `check_on_wq`.

**Comment by techraf** [comment] 2016-07-21 01:28
Frankly speaking I am losing interest in further exploring this case. The versions and their behaviour differ, but as long as the check-on-quit happens, it's more productive to actually improve the quality of the scripts to prevent Syntastic from complaining rather than disabling it.

I've learnt a lot about Vim debugging though, so I appreciate your help.

If you feel there is a need to troubleshoot that, I would be happy to assist (with a lower priority though). Please let me know.

**Comment by lcd047** [comment] 2016-07-21 03:57
@techraf The relevant part of the code hasn't changed in syntastic in a long time, and on the other hand there are other reports at [vi.stackexchange][vi.se] about people missing quit events in various contexts.  Personally I can't reproduce any of these, and I have no useful data to even hint at what to look for.  Maybe the problem will be found to be in Vim eventually, or perhaps somebody will come up with a more revealing way to reproduce the problem.  It's ok with me to close this for now.

[vi.se]: http://vi.stackexchange.com/

**Closed** 2016-07-22 03:43 UTC
