### ISSUE TITLE
:lnext clears editor for haskell and does not show up in .py

### ISSUE THREAD

**Issue by elvis-sik** [scrooloose/syntastic#1450] opened 2015-06-16 03:33 UTC
I installed syntastic today. It gives me some hints as to how to improve my Haskell code. I try :lnext to navigate. My code is gone, as is the .swp file. If I close it and reopen, it is there. But I cannot use :lnext nor :lprevious.

Also, pylint is in path (:!echo $PATH), but I get no linting in .py files.

I am using Vim  7.4, syntastic 3.6.0-93

**Comment by lcd047** [comment] 2015-06-16 04:27
Are you using the [recommended settings][settings]?

[settings]: https://github.com/scrooloose/syntastic#settings

**Comment by elvis-sik** [comment] 2015-06-16 11:50
I am. I found out workarounds for both problems.

First, the Haskell one was taken care of when I got rid of an accent in the directory name (i.e., "á" -> "a"). The Python one was really not seeing the $PATH I wanted. This only happens when I open my .py files by double clicking on them as opposed to opening a terminal, and then opening vim (I think this is related to the fact that i set up my PATH on .bashrc).

**Comment by lcd047** [comment] 2015-06-16 18:02
Next time please consider reporting at most one problem per thread.

Let's try to address the Python problem first.  Please open a Python file in Vim, and compare the results of `:!echo $PATH` and `:echo $PATH`.  If they differ, you can solve the problem either by configuring your desktop manager to use the correct `PATH`, or by adding a like `let $PATH='...'` to your vimrc.

The Haskell issue now.  Please restore the situation that creates the behaviour you describe in your first post.  Which checker is having problems?

**Comment by elvis-sik** [comment] 2015-06-16 19:05
I am so sorry, I wasn't sure if the protocol was "avoid creating many threads" or "avoid reporting many issues in a single thread". Are you aware of any guidelines orienting us about these open source-y matters, or should I learn by trial and error?

I realized when I double clicked to open a file (as opposed to open it through a terminal), .bashrc's PATH settings were not taken. So I transferred the PATH-setting to .profile, and it did it.

My .hs files are being handled by hlint (it says). I can reproduce it easily. My directory is called either "Pratica" or "Prática". When I leave it as the latter version, with an accent, using :lnext a single time will make the text of the file being edited disappear. It will show only "1", indicating the line number (which I set up to be always shown). If I rename it back to Pratica, I can use :lnext as expected. This happens regardless of how I start up vim, be it from the shell or from the GUI.

**Comment by lcd047** [comment] 2015-06-16 19:18
Please read this aloud: debugging syntastic is a __linear__ process.  Post at most one issue at a time.  Don't edit your answers after receiving replies, add a reply instead.  Consider answering the points I make before stating your own hypotheses about what is going on.  Don't make random changes and expect them to fix your problem.

Now, to answer your __Edit__ above: `:!` runs a shell.  A different one every time.  Setting `:!PATH=...` will not have any effect on subsequent commands.

You need to change Vim's idea of `PATH`.  Vim inherits the `PATH` either from the shell (if you run it in a terminal), or from the desktop manager (if you launch gVim with right click or whatever).  The problem is the desktop manager doesn't necessarily inherits the environment from a shell, so you'll need to either fix your desktop manager's idea of `PATH`, or override it in Vim.

To override Vim's idea of `PATH` you need to add a line like this to your vimrc:
```
let $PATH='/your:/path:/here'
```

**Comment by elvis-sik** [comment] 2015-06-16 20:46
Thanks, this is useful to know.

I should clarify that the accent problem happens only with .hs files, my .py ones run smoothly regardless of accents in their path.

**Comment by lcd047** [comment] 2015-06-17 06:27
For the accented character problem: please run `locale` in a terminal and post the output.  Then open your test file in Vim, run each of the commands below and post the output:
```vim
:set encoding? fileencoding?
:echo expand('%:p')
:echo syntastic#util#shexpand('%:p')
```

**Comment by elvis-sik** [comment] 2015-06-17 14:38
I changed some things on my .vimrc and found out I didn't have ghc-mod. I installed it. Now the behavior changed a bit. With accents, 

    1 Dice.hs|35 col 1 error| parse error on input ‘module’                       
    2 || parse error in ghcmod! Could not parse the following ghc-mod output:/home/elvis/Pr\225tica/Dice.hs: Warning: Parse error: module Found: -} > module Dice where import System.Random (Random, RandomGen, randomRs, randomR)

The given commands report 'utf-8' 'utf-8' and the correct path (with accent, no escaped character) for both of the others.

I reiterate, this problem is Haskell exclusive. I guess syntastic is not responsible for it.

**Comment by lcd047** [comment] 2015-06-17 15:19
As far as I can tell `ghc-mod` fails because of a configuration problem, but that's between Haskell and your locales.  `hlint` on the other hand is in a very different situation, syntastic does some munging to get it to report the correct paths, and I'm not convinced said munging is 100% bulletproof.

But, if you don't feel like pursuing this any further, feel free to close the issue.

**Comment by elvis-sik** [comment] 2015-06-17 19:31
Well, I'd like to be able to use accents, if you feel like you can help we can try and investigate. Otherwise, I'll simply stop using accents, and you can close the issue.

**Comment by lcd047** [comment] 2015-06-18 10:43
Please try commit b609b3b.  It's supposed to work around __a__ problem (which may or may not be the one you're seeing :) ) related to accented characters for `ghc-mod`.  I can't reproduce your results for `hlint`.

**Closed** 2015-06-25 08:01 UTC
