### ISSUE TITLE
Syntastic breaks compilation of Ada code

### ISSUE THREAD

**Issue by ampoffcom** [scrooloose/syntastic#1455] opened 2015-06-24 06:08 UTC
When opening a adb-source file with vim 7.4 and syntastic enabled, the next compilation fails with a linker error.

How to reproduce

a) Syntastic disabled
1. Create a new or open an existing adb file with vim
2. write without changing something
3. quit
4. gnatmake test.adb
5. success

b) Syntastic enabled
1. Create a new or open an existing adb file with vim
2. write without changing something
3. quit
4. gnatmake test.adb
5. linker error with "undefined reference to `main'"

When editing a file that contains errors, e.g. missing semi-colon, syntastic displays an error message. This is expected behaviour.

**Comment by lcd047** [comment] 2015-06-24 08:40
There is nothing in syntastic that changes the contents of the files being checked.  If you're seeing changes, this is either the result of an interaction with another plugin, some unintended interaction with Vim's UI, or a bug in Vim.  Can you reproduce the problem if you disable __all__ other plugins except syntastic?  Can you please post a minimal file that illustrates the problem?

**Comment by ampoffcom** [comment] 2015-06-24 11:02
Update: I noticed when I :w the file, vim tries to compile the file, i.e. there is a .ali and a .o-file, but no compilation. When I delete both files gnatmake succeeds.

All plugins disabled except vundle, see vimrc here https://gist.github.com/ampoffcom/ed5ad53e5422cb54eb37

Minimal example here https://gist.github.com/ampoffcom/938df72119a72ad617bf

**Comment by lcd047** [comment] 2015-06-24 14:10
By default, syntastic runs something like this against your files:
```sh
gcc -c -x ada -fsyntax-only file.adb
```
I would have (naively) assumed that `-fsyntax-only` tells `gcc` not to produce any output files, but apparently I was wrong, this indeed produces `.o` and `.ali` files.  I'm afraid I don't know anything about Ada, or the Ada backend of gcc.  If there is a way to disable the generation of these files, I'd like to know about it, to add it to syntastic.  Perhaps ask on some Ada forum?  Not sure what else to tell you; sorry I'm not of much help.

**Comment by ampoffcom** [comment] 2015-06-25 06:06
Thanks for your reply. I'll investigate further.

**Comment by lcd047** [comment] 2015-06-25 07:59
Fixed in dbb28cd.

**Closed by lcd047** 2015-06-25 07:59 UTC
