### ISSUE TITLE
Error detected while processing function <SNR>19_BufWritePostHook[4]..<SNR>19_UpdateErrors [15]..<SNR>19_CacheErrors[29]..20:

### ISSUE THREAD

**Issue by bwhicks** [scrooloose/syntastic#1885] opened 2016-10-04 23:47 UTC
Hi,

As of update 9648145ab155a6b114c354fe790fad484ad02f5a , I'm getting the following error when writing a buffer:

>Error detected while processing function <SNR>19_BufWritePostHook[4].. 
> <SNR>19_UpdateErrors
>[15]..<SNR>19_CacheErrors[29]..20:
>line    7:
> E713: Cannot use empty key for Dictionary

Reverting to 59cc80a8f7f7544a364814622dc62efd00d17ca4 resolves the issue.

Thanks for a wonderful coding resource!

**Comment by lcd047** [comment] 2016-10-05 07:03
I can't reproduce the problem with the current master HEAD, and the error message is rather cryptic.  It would help if you could tell me what "function 20" is in the above stack trace.  Sadly Vim makes that a pain in the rear.  One way to do it would be to enable profiling (cf. `:h syntastic-profiling`), trigger the bug in a minimal scenario, then search the logs for `^FUNCTION 20()` and locate the corresponding piece of code in `plugin/syntastic.vim`.  Or just upload the logs somewhere and post the link.

Another way to do it would be to disable all other plugins, run Vim as `vim -V12log file`, trigger the bug, and again, locate function 20, or upload the logs and post the link.

**Comment by lcd047** [comment] 2016-10-05 07:16
Never mind.  Please update to the current master HEAD and try again.

**Comment by gzmask** [comment] 2016-10-05 07:46
same error when saving upon my own init.vim file:
https://github.com/gzmask/my-neovim/blob/master/init.vim

"init.vim" 60L, 1642C written
Error detected while processing function <SNR>56_BufWritePostHook[4]..<SNR>56_UpdateErrors[15]..<SNR>56_CacheErrors[29]..303:
line    7:
E713: Cannot use empty key for Dictionary
Press ENTER or type command to continue

**Comment by lcd047** [comment] 2016-10-05 07:55
@gzmask Are you using the current master HEAD, i.e. 75b1095?  Can you reproduce the problem with plain Vim (rather than Neovim)?

**Comment by nicoe** [comment] 2016-10-05 10:42
@lcd047 I have the same issue. Both with neovim and vim.

**Comment by dkim87** [comment] 2016-10-05 10:48
Just updated and have the same issue with neovim. Not in vim though I should check.

**Comment by lcd047** [comment] 2016-10-05 10:49
@nicoe all of you guys omit the most important detail: are you using commit 75b1095?

**Comment by dkim87** [comment] 2016-10-05 10:51
I use vimplug and when I run :PlugSnapshot, it says:
`silent! let g:plugs['syntastic'].commit = '75b1095'`
So I guess I'm using it.

**Comment by nicoe** [comment] 2016-10-05 11:04
> @nicoe all of you guys omit the most important detail: are you using commit 75b1095?

Of course I am why would I bother commenting otherwise ?

**Comment by lcd047** [comment] 2016-10-05 11:05
@dkim87 Your faith in your plugin manager is heart-warming, but you really should check with `git rev-parse HEAD`.

Anyway, that error doesn't make sense for 75b1095, since the key for the dictionary is set [a few lines above](https://github.com/scrooloose/syntastic/blob/master/plugin/syntastic/checker.vim#L186).  I also can't reproduce the problem.  So you'll have to give me something more actionable than the error above. _shrug_

**Comment by lcd047** [comment] 2016-10-05 11:07
Can you people reproduce the problem with Vim (not neovim), and all other plugins disabled?  What is your configuration, and what checker is being run?

**Comment by dkim87** [comment] 2016-10-05 11:15
Yeap, I cd to .vim/plugged/syntastic and checked the commit with `git rev-parse HEAD`. Here is the result: `75b1095586b1cb685ccb0e69004bcd4ae75b37da`
Thanks for the instruction.

**Comment by nicoe** [comment] 2016-10-05 11:21
> Can you people reproduce the problem with Vim (not neovim)

Yes

> and all other plugins disabled?

Yes

> What is your configuration, and what checker is being run?

vimlint

Here's the minimal .vimrc that results in the error:
```
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/syntastic'
call plug#end()

let g:syntastic_check_on_open = 1
```

I just edit this .vimrc file.

**Comment by dkim87** [comment] 2016-10-05 11:28
> Can you people reproduce the problem with Vim (not neovim)
No
> and all other plugins disabled?
For Vim, as mentioned above, no. For Neovim, Yes
> What is your configuration, and what checker is being run?
Shame on me, I do not know about this.

One interesting point: I only have this error message when I open .vimrc (which I symlinked to dotfiles/init.vim). With the other file extensions such as .c, .txt, .csv it works just fine.

**Comment by lcd047** [comment] 2016-10-05 11:30
@nicoe I'm afraid I still can't reproduce the problem.  What version of Vim are you using?

**Comment by dkim87** [comment] 2016-10-05 11:35
I realized that I'm having this problem only with .vimrc, init.vim, plugins.vimrc, mappings.vimrc, etc. (vim-related files). I tried other extensions such as .c, .txt, .md, and even created some random extension like .asdf and it didn't reproduce the problem.

**Comment by lcd047** [comment] 2016-10-05 11:38
@dkim87 Neovim "should work", but it isn't supported.  As in, I don't have Neovim, and if you can't reproduce the problem with plain Vim I have no way to help you.  Other people may be able to trace the problem though.

@nicoe: When you have no other plugins than syntastic, `vimlint` shouldn't be enabled.  Just saying.

**Comment by nicoe** [comment] 2016-10-05 11:40
> What version of Vim are you using?

Good catch.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:35:24)
Included patches: 1-488, 576

It's an debian server running jessie.

I installed vim on my laptop:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2016 01:54:12)
Included patches: 1-3

The issue is **not** present on my laptop when using vim. But it appears when using neovim.
As @dkim87, it only happens for vim files. I guess there is a fix in Vim 8.0 that is not in neovim.

**Comment by nicoe** [comment] 2016-10-05 11:42
> When you have no other plugins than syntastic, vimlint shouldn't be enabled. Just saying.

I kinda guess it was vimlint, what else could it be ?

**Comment by lcd047** [comment] 2016-10-05 11:49
This might be related to a quirk of the `vimlint` checker.  Please try upgrading to 4c4e516.

**Comment by dkim87** [comment] 2016-10-05 11:49
I got a hint from nicoe and tried vim 7.4 and succeed in reproducing the problem.

**Comment by dkim87** [comment] 2016-10-05 11:54
I use MacOS X and brew vim. I 'cd'ed to /usr/local/Cellar/vim/7.4.2290/bin and run 
$./vim ~/helloworld.c and it says on the command line 
E484: Can't open file /usr/local/share/vim/syntax/syntax.vim 

If I 'cd' to /usr/local/Cellar/vim/8.0.0019/bin and do the same then it does not produce any error. So it is probably a vim7.4 and vim 8.0 compatibility issue.

**Comment by lcd047** [comment] 2016-10-05 12:00
> E484: Can't open file /usr/local/share/vim/syntax/syntax.vim

This means your Vim 7.4.2290 can't find syntastic, for whatever reasons (no plugin manager, renamed runtime, renamed init files, ...).  Not exactly syntastic's fault. :smile:

> If I 'cd' to /usr/local/Cellar/vim/8.0.0019/bin and do the same then it does not produce any error.

This means your Vim 8.0.19 _can_ find syntastic.  Nice, but not making any progress.

Can you still trigger the problem with 4c4e516, as I said above?

**Comment by dkim87** [comment] 2016-10-05 12:02
`4c4e516` solved the problem at least for me! Now both my Neovim and vim 8.0 does not generate any problem. Thank you!

**Comment by nicoe** [comment] 2016-10-05 12:09
> This might be related to a quirk of the vimlint checker. Please try upgrading to 4c4e516.

This changeset fixed the problem with my (rather old) vim and with neovim. Thank you.
Ain't that a bit strange that vim8 does not have the issue ?

**Comment by lcd047** [comment] 2016-10-05 12:10
Ok.  Does that fix the problem for everybody else?

**Comment by lcd047** [comment] 2016-10-05 12:13
@nicoe Yup, it's actually highly relevant where the difference comes from.  I'll try to find out.

**Comment by lcd047** [comment] 2016-10-05 12:29
Ok, I now have the full picture.  The difference is Vim 8.0 and late 7.4 can, actually, take empty strings as dictionary keys, while Neovim can't.  As it turns out, the `vimlint` was the only checker that triggered that problem, because of a quirk.  The problem _was_ present in Vim 8.0 as well as elsewhere, but it didn't trigger an exception, and it was irrelevant to the later code.  I'm confident it's fixed now.

**Closed by lcd047** 2016-10-05 12:29 UTC

**Comment by bwhicks** [comment] 2016-10-05 12:54
Thanks for getting this. I was out this morning and just saw the thread and the fact it was super quickly handled. 4c4e516e1ddd7c1b04624e26be1bbb41bc6b7edb corrects it for me with vim 7.4 on Darwin.
