### ISSUE TITLE
BufWritePostHook failures block whole Vim workflow

### ISSUE THREAD

**Issue by ain** [scrooloose/syntastic#1592] opened 2015-11-05 13:53 UTC
My whole workflow is currently broken because of the following error:

```
Error detected while processing function <SNR>110_AutoUpdate..<SNR>110_ProcessFile:                                                                                                               
line   40:                                                                                                                                                                                        
E482: Can't create file /var/folders/6f/1zt06xc97cv5kbw8lr8grtr80000gp/T/vXqq2Z7/27.js                                                                                                            
```
It's coming up by itself time to time and it has become a blocker.

Platform:
```
syntastic 03c058ea52d5c77ce6335f0ab16aa6559a3082ca
$ tmux -V
tmux 2.0
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 28 2015 11:08:36)
MacOS X (unix) version
Included patches: 1-729
Compiled by ain@Ains-MacBook-Pro.local
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -DMACOS_X_UNIX  -pipe -Os -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L. -L/opt/local/lib -Wl,-headerpad_max_install_names   -fstack-protector -L/opt/local/lib  -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -o vim        -lncurses -liconv -lintl -framework Cocoa   -L/opt/local/lib -Wl,-headerpad_max_install_names  -fstack-protector  -L/opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -L/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -u _PyMac_Error /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python   -lruby.2.0.0 -lobjc -L/opt/local/lib

**Comment by ain** [comment] 2015-11-05 15:51
Another failure:
```
"src/iptools-jquery-mlhmenu.js" 250L, 7099C written                                                                                                                                                                                                                                   
Error detected while processing function <SNR>52_BufWritePostHook..<SNR>52_UpdateErrors..<SNR>52_CacheErrors..255..254..SyntaxCheckers_javascript_jscs_GetLocList..SyntasticMake..syntastic#util#system:                                                                              
line    9:                                                                                                                                                                                                                                                                            
E484: Can't open file /var/folders/6f/1zt06xc97cv5kbw8lr8grtr80000gp/T/vI3qUbN/58                                                                                                                                                                                                     
Error detected while processing function <SNR>52_BufWritePostHook..<SNR>52_UpdateErrors..<SNR>52_CacheErrors:                                                                                                                                                                         
line   35:                                                                                                                                                                                                                                                                            
E170: Missing :endfor                                                                                                                                                                                                                                                                 
Error detected while processing function <SNR>52_BufWritePostHook..<SNR>52_UpdateErrors:                                                                                                                                                                                              
line   15:                                                                                                                                                                                                                                                                            
E171: Missing :endif         
```

**Comment by ain** [comment] 2015-11-05 15:52
So it clearly seems to be happening over `.jscsrc`. The one in question can be seen [here](https://github.com/interactive-pioneers/iptools-jquery-mlhmenu/blob/master/.jscsrc). Was working perfectly fine before the recent releases.

**Comment by lcd047** [comment] 2015-11-05 16:03
What is `AutoUpdate`?
```sh
$ fgrep -ir AutoUpdate syntastic | wc -l
0
```

**Comment by ain** [comment] 2015-11-09 14:12
Another one:
```
Error detected while processing function <SNR>53_BufWritePostHook..<SNR>53_UpdateErrors..<SNR>53_CacheErrors..255..254..SyntaxCheckers_ruby_mri_GetLocList..SyntasticMake..syntastic#util#system:
line    9:
E484: Can't open file /var/folders/6f/1zt06xc97cv5kbw8lr8grtr80000gp/T/vThet5t/18
Error detected while processing function <SNR>53_BufWritePostHook..<SNR>53_UpdateErrors..<SNR>53_CacheErrors:
line   35:
E170: Missing :endfor
Error detected while processing function <SNR>53_BufWritePostHook..<SNR>53_UpdateErrors:
line   15:
E171: Missing :endif
```

**Comment by lcd047** [comment] 2015-11-09 14:14
Are you ready yet to disclose what is `AutoUpdate`?  It isn't part of syntastic.

**Comment by ain** [comment] 2015-11-09 14:19
You're right, AutoUpdate is unrelated and designates from `tagbar.vim`:
```
$ fgrep -ir AutoUpdate . 
./bundle/tagbar/autoload/tagbar.vim:        call s:AutoUpdate(fnamemodify(expand('%'), ':p'), 0)
./bundle/tagbar/autoload/tagbar.vim:    call s:AutoUpdate(curfile, 0)
./bundle/tagbar/autoload/tagbar.vim:                    \ s:AutoUpdate(fnamemodify(expand('<afile>'), ':p'), 1)
./bundle/tagbar/autoload/tagbar.vim:                    \ s:AutoUpdate(fnamemodify(expand('<afile>'), ':p'), 0)
./bundle/tagbar/autoload/tagbar.vim:    call s:AutoUpdate(curfile, 0)
./bundle/tagbar/autoload/tagbar.vim:" s:AutoUpdate() {{{2
./bundle/tagbar/autoload/tagbar.vim:function! s:AutoUpdate(fname, force) abort
./bundle/tagbar/autoload/tagbar.vim:    call s:debug('AutoUpdate called [' . a:fname . ']')
./bundle/tagbar/autoload/tagbar.vim:    call s:debug('AutoUpdate finished successfully')
./bundle/tagbar/autoload/tagbar.vim:        call s:AutoUpdate(fnamemodify(expand('%'), ':p'), 1)
```
The other problem mentioned points to syntastic though:
```
$ fgrep -ir SyntaxCheckers_ruby_mri_GetLocList . 
./bundle/syntastic/syntax_checkers/ruby/mri.vim:function! SyntaxCheckers_ruby_mri_GetLocList() dict
```

**Comment by lcd047** [comment] 2015-11-09 14:35
Can you reproduce the problem without `tagbar`?

**Comment by lcd047** [comment] 2015-11-09 15:18
Commit 85cde92 should provide a workaround.

**Comment by ain** [comment] 2015-11-09 15:44
Will test for sure, thanks!

**Comment by burningTyger** [comment] 2015-11-11 19:19
Hi, I have (a | the same) problem. Cropped up after I last updated my plugins:

```
Error detected while processing function <SNR>37_BufWritePostHook..<SNR>37_UpdateErrors..<SNR>37_CacheErrors..15..14..SyntaxCheckers_slim_slimrb_GetLocList..SyntasticMake..syntastic#preprocess#slimrb:                                      
line   24:                                                                                                             
E684: list index out of range: 0                                                                                       
Error detected while processing function <SNR>37_BufWritePostHook..<SNR>37_UpdateErrors..<SNR>37_CacheErrors:          
line   35:                                                                                                             
E170: Missing :endfor                                                                                                 
Error detected while processing function <SNR>37_BufWritePostHook..<SNR>37_UpdateErrors:
line   15
E171: Missing :endif   
```

**Comment by lcd047** [comment] 2015-11-11 19:26
@burningTyger Not even remotely related.  Please see #1587.

**Comment by ain** [comment] 2015-11-11 19:59
@lcd047 `AutoUpdate` issue it was a `tagbar` problem, I've killed it and it has been stable. 

I have not tested the `BufWritePostHook` workaround yet.

**Comment by burningTyger** [comment] 2015-11-11 20:00
@lcd047 @ain, sorry, you're right. I just updated again and it seems to be fixed by now. Must have thought I updated yesterday but then it probably was the other computer. I'm getting mixed up lately with workstations.

**Comment by ain** [comment] 2015-11-11 20:13
No worries @burningTyger, I've exactly the same problem, updating 2 machines in parallel and I was also able to reproduce these things on both.

**Closed** 2015-11-12 06:37 UTC
